sudo: false
language: python
python:
  - "3.5"
env:
  - TOXENV=py27-django17
  - TOXENV=py34-django17
  - TOXENV=py27-django18
  - TOXENV=py34-django18
  - TOXENV=py35-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
install:
  - pip install -q -U pip setuptools tox coveralls
script:
  - tox
after_success:
  coveralls
