sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -q -U pip setuptools tox tox-travis
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
